### ISSUE TITLE
ESC key not working

### ISSUE THREAD

**Issue by kz81** [rizonesoft/Firemin#2] opened 2017-12-29 01:47 UTC
Hello,
I just found out about Firemin - outstanding program! This would make my everyday PC work so much more effective. However, there seems to be some bug, at least on my system.
Whenever Firemin is running, I cannot use the ESC key.
I had ESC issues with Firefox and Intel Graphics drivers, both solved. Both were related to hotkey settings done by the respective applications. When I quit Firemin, ESC works well. Then when I start Firemin again, ESC stops working. This is absolutely reproducible on my PC.
(HP Notebook with Win 8.1 Pro 64)

Any solution would be appreciated very much!
Kind regards & thank you,

Karl

**Comment by rizonesoft** [comment] 2017-12-29 08:17
@kz81 I could not reproduced the issue, but did implement a fix a version ago. Are you using the latest version available from [here](https://www.rizonesoft.com/downloads/firemin/).

**Comment by kz81** [comment] 2017-12-29 09:17
Thank you for your quick reply!
- I had tried to install the latest version, but when I downloaded it from https://www.rizonesoft.com/download/3949/ yesterday, it said "corrupted file", so I used the version before
- Now I tried it again, and this time it was NOT corrupted AND it fixed the issue!

Thank you so much! I wonder why FF staff didn't manage to solve the memory issue themselves.
Plus, I wonder why your software is not more popular. If you have a donation link, please post here - would like to support the great work!

**Comment by kz81** [comment] 2017-12-29 09:20
Donation done. Thank you!

**Comment by rizonesoft** [comment] 2017-12-29 10:47
@kz81  I'm glad it was resolved. Thank you for your support, it is greatly appreciated. 😄

**Comment by rizonesoft** [comment] 2018-03-19 06:25
Closing this issue.

**Closed by rizonesoft** 2018-03-19 06:25 UTC
